src/Mailgun/Connection/RestClient.php
Adds the actual response message to the errors thrown on 400, 401 and
404 response codes. This provides a lot more useful info than the
current messages. The message doesn’t really give you much to go on. I
spent hours trying to find what I did wrong, double checking my API
keys and looking up the error on google.
=> Fix for #71: Show response message on 400, 401 and 404.

src/Mailgun/Mailgun.php, tests/Mailgun/Tests/Mock/Connection/TestBroker.php, tests/Mailgun/Tests/Mock/Mailgun.php
As read on http://blog.mailgun.com/default-api-version-now-v3/ the default API version is now 3.
I noticed this update was not reflected in this repository, so i decided to create my first ever pull request with this small edit!
=> Updated default API version from v2 to v3

.travis.yml, composer.json, src/Mailgun/Connection/RestClient.php, tests/Mailgun/Tests/MailgunTestCase.php, tests/Mailgun/Tests/Mock/Connection/TestBroker.php
Guzzle5 and some other neat tricks makes the `RestClient` a lot cleaner. 
This PR does not change the API nor does it add any features. I think this is a necessary update because it reduces the number of dependencies in my application. I don't want dependencies on both Guzzle3 and Guzzle5. 
Also, with the new Guzzle we do no longer suffer from the bug temporarily fixed [here](https://github.com/mailgun/mailgun-php/commit/8d23a5bb9f36db8594836329b3905d0dfb137da7)
=> Updated to Guzzle5

src/Mailgun/Mailgun.php, tests/Mailgun/Tests/MailgunTest.php
If someone invokes the webhook verification routine without any POST data, three notices are thrown:
PHP Notice:  Undefined index: timestamp in /home/z38/dev/mailgun-php/src/Mailgun/Mailgun.php on line 91
PHP Stack trace:
PHP   1. {main}() /home/z38/dev/mailgun-php/test.php:0
PHP   2. Mailgun\Mailgun->verifyWebhookSignature() /home/z38/dev/mailgun-php/test.php:7
PHP Notice:  Undefined index: token in /home/z38/dev/mailgun-php/src/Mailgun/Mailgun.php on line 91
PHP Stack trace:
PHP   1. {main}() /home/z38/dev/mailgun-php/test.php:0
PHP   2. Mailgun\Mailgun->verifyWebhookSignature() /home/z38/dev/mailgun-php/test.php:7
PHP Notice:  Undefined index: signature in /home/z38/dev/mailgun-php/src/Mailgun/Mailgun.php on line 92
PHP Stack trace:
PHP   1. {main}() …
=> Fix notices on empty webhook requests

src/Mailgun/Mailgun.php
Updated the docblock to include what the `\Mailgun\Mailgun::sendMessage` returns and throws. 
Mentioned in issue #120
=> Updated docblock for sendMessage 

src/Mailgun/Mailgun.php
Strict compare of signature with the computed value, to fix the a security risk.
Previously fixed vulnerability:
- https://github.com/laravel/laravel/commit/ba0cf2a1c9280e99d39aad5d4d686d554941eea1
- [wordpress #28054](https://core.trac.wordpress.org/changeset/28054) ([CVE-2014-0166](https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2014-0166))
Related discussions:
- https://news.ycombinator.com/item?id=9484757
- https://medium.com/@barryvdh/csrf-protection-in-laravel-explained-146d89ff1357
=> Strict check of signature

src/Mailgun/Connection/RestClient.php, tests/Mailgun/Tests/Mock/Connection/TestBroker.php
Fix issue #122
If the $body is an array we make sure to build in to a string query and add the correct header
=> Build a string query form array

README.md, composer.json, src/Mailgun/Connection/RestClient.php
This will make sure we are totally decoupled from Guzzle. It will also make installation a bit easier since php-http/discovery:1.0 does no longer depend on Puli.
=> Do not depend on Guzzle/PSR7

src/Mailgun/Messages/BatchMessage.php
To avoid `field declared dynamically` and `field not found` warnings in IDEs
=> Declare endpointUrl field

tests/Bootstrap.php
| Q             | A      |
|---------------|--------|
| Branch        | v2.1.2 |
| Bug fix?      | No     |
| New feature?  | No     |
| BC breaks?    | No     |
| Deprecations? | No     |
| Tests pass?   | Yes    |
| Fixed tickets |     |
| License       |        |
| Doc PR        |        |
As part of the PSR Standards, reported by PHP Code Sniffer, we should use `include` instead of `require` when possible, so this PR is applying this update.
=> Apply PSR Standards to tests/ too

tests/Mailgun/Tests/Functional/MockedMailgun.php, tests/Mailgun/Tests/Functional/MockedRestClient.php, tests/Mailgun/Tests/Functional/SendMessageTest.php
This will be a foundation for the functional tests. It is a rewrite of what proposed in #151.
Normally one would setup and mock both a Mailgun object and a RestClient object and then use something like: 
```php
$mock->expects($this->once())
->method('send')
->with(
$this->equalTo('POST'),
$this->stringContains('domain'),
$this->equalTo([]),
$this->callback(function($files){
return $files[0] == ['name'=>'to', 'contetns'=>'foobar]
})
);
```
Instead I choose to be more pragmatic and make it easier to write tests. Is this a good foundation to build on?
=> Added functional tests

README.md
No need for users to install `php-http/message` manually since it's [already in package deps list](https://github.com/mailgun/mailgun-php/blob/master/composer.json#L8)
=> Remove php-http/message from installation guide, it's already in deps

src/Mailgun/Messages/BatchMessage.php, tests/Messages/BatchMessageTest.php
This PR is replacing the old one (https://github.com/mailgun/mailgun-php/pull/118) providing the expected PHPUnit test to validate the update, and make sure we get a valid response when we don't provide an array with the first name and last name.
This PR is a request of @Nyholm asking for a Pull Request that has the expected tests too.
=> Make sure $variables is an array in addRecipient()

.gitignore, .travis.yml, composer.json, phpunit.xml.dist, src/Mailgun/Api/AbstractApi.php, src/Mailgun/Api/Domain.php, src/Mailgun/Mailgun.php, src/Mailgun/Resource/Api/Domain/ComplexDomain.php, src/Mailgun/Resource/Api/Domain/Credential.php, src/Mailgun/Resource/Api/Domain/CredentialListResponse.php, src/Mailgun/Resource/Api/Domain/DeliverySettingsResponse.php, src/Mailgun/Resource/Api/Domain/DeliverySettingsUpdateResponse.php, src/Mailgun/Resource/Api/Domain/DomainDnsRecord.php, src/Mailgun/Resource/Api/Domain/DomainListResponse.php, src/Mailgun/Resource/Api/Domain/SimpleDomain.php, src/Mailgun/Resource/Api/SimpleResponse.php, tests/Api/StatsTest.php, tests/Api/TestCase.php, tests/Integration/DomainApiTest.php
This adds the `domains` API routes and the response objects that belong with it. Also fixes up some testing stuff, updates some requirements, and repairs some typos.
Still need:
=> Domains API, #187

src/Mailgun/Api/Event.php, src/Mailgun/Api/Pagination.php, src/Mailgun/Mailgun.php, src/Mailgun/Resource/Api/Event/Event.php, src/Mailgun/Resource/Api/Event/EventResponse.php, src/Mailgun/Resource/Api/PaginationResponse.php
This will fix #188 
Do you like the pagination?
```php
$result = $mg->event()->get('domain');
$resultNext = $mg->event()->getPaginationNext($result);
```
Below is an alternative. It does not work as well for someone that does not use the domain objects. And it makes the `EventResponse` a service somehow and not a value object. 
```php
$result = $mg->event()->get('domain');
$resultNext = $result->paginationNext($mg->event());
```
=> Added Event API with pagination

src/Mailgun/Api/Domain.php, src/Mailgun/Api/HttpApi.php, src/Mailgun/Api/Message.php, src/Mailgun/Api/Stats.php, src/Mailgun/Api/Webhook.php, src/Mailgun/Deserializer/ModelDeserializer.php, src/Mailgun/Mailgun.php, src/Mailgun/Resource/Api/Message/SendResponse.php, src/Mailgun/Resource/Api/Message/ShowResponse.php
This will add the missing Message API. The old message builders will still work. 
(Sorry for including the change to `$this->safeDeserialize($response, ...)` in this PR.)
Fixes #168
=> Messages api

src/Mailgun/Api/HttpApi.php
In some cases, the API returns a response without any content (e.g. when supplying an invalid key).
Example:
```php
$mailgun = new Mailgun\Mailgun('invalidkey');
$mailgun->routes()->index(); // throws error/exception
```
In such cases, a fatal error was thrown because `null` was passed to `ErrorResponse::create()` (PHP 5.6) or an exception was thrown when the empty body was decoded ([PHP >7.0](https://3v4l.org/IalIO)).
It might be necessary to include a similar fix for `ArrayDeserializer` as well.
=> Avoid fatal error when deserializing unauthorized requests

src/Mailgun/Api/HttpApi.php, tests/Integration/DomainApiTest.php
The integration tests for the Domain API were failing because non-GET requests did not work properly and in cases when an error occured, a generic `ErrorResponse` was actually returned.
=> Fix integration tests for domain API

src/Mailgun/Model/Route/Response/UpdateResponse.php, tests/Api/TestCase.php, tests/Integration/RouteApiTest.php
To ensure that the Route API won't break in the future, this patch adds some integration tests. The tests cover the whole lifecycle of a route (create, update and delete).
=> Add integration tests for Route API

phpunit.xml.dist
To ensure that the integration tests don't fall behind the current development, it might make sense to enable them again. The testsuite only covers a small subset of the whole API so updating it won't cause much work and ensures that this library is working (and continues to).
=> [RFC] Re-enable integration tests

src/Mailgun/Messages/MessageBuilder.php, tests/Messages/BatchMessageTest.php, tests/Messages/MessageBuilderTest.php
Due to your recent API update, named addresses with special chars (like parentheses) are now rejected if they are surrounded by simple quotes
They must be surrounded by double quotes
'Whoever (SomeCompany)' <some@address.com> is no longer valid and will be rejected by your API
"Whoever (SomeCompany)" <some@address.com> is valid and will be OK
=> fix: named addresses must be surrounded by double quotes

README.md
ArrayHydrator was spelt wrong causing the example not to work
=> Fixed typo in ArrayHydrator documentation

src/Mailgun/Exception/HttpClientException.php, src/Mailgun/Exception/HttpServerException.php
A complaint I received is that it was no longer easy to determine, for example, if a bounce a user is trying to `GET` is not found or if another API error occurred. This should help to ease that issue.
=> Expose response code from HttpClientException

src/Mailgun/Mailgun.php
The `sendMessage()` method will be replaced by `Mailgun->messages()->send()` see issue #382
=> Fix for deprecation message for `sendMessage()`

src/Mailgun/Messages/README.md
It feels a bit cleaner to me like this.
Or would it look better like this =>
```
// After 1,000 recipients, Batch Message will automatically post your message to 
// the messages endpoint. 
```
=> Removed unnecessary new lines

src/Mailgun/Api/Domain.php
According to issue #397 the stmp params are optionals in the creation of a domain
=> Update POST domain/create with optional params

src/Mailgun/Model/Stats/TotalResponse.php, src/Mailgun/Model/Stats/TotalResponseItem.php, tests/Api/StatsTest.php, tests/Api/TestCase.php
Currently when using the `stats->total()` method, it always returns an empty array for stats.
- There was an issue in the code, with a wrong isset check.
- There was a second issue on `TotalResponseItem` as some constructor parameters are typed as array but in some case, the null value is passed instead.
There is also a third issue (I don't take time to resolve as it's more difficult), as we can't specified a list of stats events to retrieve from the api as the query is not formatted as expected, which makes the method only usable with one event, not several.
Mailgun expects `/v3/xxx/stats/total?duration=100d&event=delivered&event=failed`
Instead the mailgun-php library formats it this way: `/v3/xxx/stats/total?duration=100d&event%5B0%5D=delivered&event%5B1%5D=failed`
As fixing this …
=> Fixed stats retrieval

src/Mailgun/Model/Domain/AbstractDomainResponse.php
Fixed minor bug introduced in #420. 
FYI @Eugst, We missed this in the review.
=> Make sure we do not instantiate an abstract class.

src/Mailgun/Model/Tag/Tag.php, tests/Model/Tag/TagTest.php
I just ran into this bug when attempting to call `$mailgun->tags()->index('my.domain.com')`. Fixes #480.
=> Fix type error when creating tags 

src/Mailgun/Message/BatchMessage.php, src/Mailgun/Message/MessageBuilder.php
Makes using MessageBuilder and BatchMessage easier.
No potential BC breaks as all changed methods were originally void.
In addition, this fixes a few wrongly specified `@return string` PHPDoc annotations above void methods (by replacing them with now correct `@return MessageBuilder`).
Exceptions are methods `setDeliveryTime` and `addCustomParameter` which return formatted time and custom parameter value. Their return values were not changed and could be changed for a getter in the next major version (BC break).
=> Fluent interface for MessageBuilder and BatchMessage

src/Mailgun/Message/MessageBuilder.php
Continuing cleanup from https://github.com/mailgun/mailgun-php/pull/504
Not sure about formatting of `@deprecated` annotations, can be changed.
=> MessageBuilder setters entirely fluent

src/Mailgun/Api/Message.php, tests/Api/MessageTest.php
$message could contain a large email text that if sent to is_file it could break with this error:
` is_file(): File name is longer than the maximum allowed path `
This validation prevents using is_file if the $message is longer than the allowed path.
=> fix: Validate file name length

.travis.yml
This test will fail until we release 3.0 because we currently have made many BC breaks.
=> Added test for BC breaks

.github/main.workflow
This will fix #529 
This has to wait until the Github has rolled out the "Github action" feature for the mailgun organization.
=> Added PHPStan action

src/Mailgun.php
Hey @Nyholm 
I think that the PR to build the Mailing List integration (https://github.com/mailgun/mailgun-php/pull/514) didn't include the call to get access to all API Endpoints; adding it now.
Cheers,
=> Missing method for the MailingList API endpoints?

src/HttpClient/Plugin/HistoryTrait.php
because `\Http\Client\Common\HttpMethodsClientInterface` is an interface, not a class and `class_exists` returns `false` even if interface is actually exists since PHP version 5.0.2
=> Fixes #573

src/Api/Domain.php, src/Api/Event.php, src/Api/MailingList.php, src/Api/Route.php, src/Api/Tag.php
This should fix https://github.com/mailgun/mailgun-php/issues/461
I've added the assets to validate the limits for pagination according to the responses that I got from Mailgun support team.
The check validates a range, to match with the existing checks that we have for suppressions, that were added during the development phase of those features.
=> Mailgun-461: Validate limits

src/Message/MessageBuilder.php, tests/Message/MessageBuilderTest.php
As detailed in previous PR, the attachment and inline image new names are expected to be associated to the 'filename' key by Message.php
=> Fix attachment and inline image renaming

src/Api/Domain.php, tests/Api/DomainTest.php
Added support for the force_dkim_authority parameter when adding/creating a new Mailgun domain.
=> Force dkim authority

src/Api/MailingList.php, src/Model/MailingList/MailingList.php, tests/Api/MailingListTest.php
When creating new Mailing Lists via the SDK, it's not possible to explicitly set the 'reply_preference' parameter. As a result, lists created via the SDK will always default to reply_preference = list.
I've updated the following classes to add support for this parameter when creating new mailing lists:
- Mailgun\Model\MailingList\MailingList
- Mailgun\Api\MailingList
- Mailgun\Tests\Api\MailingListTest
This PR doesn't extend to the update method, although I suppose it would be near trivial to make the necessary changes to the API class and its test class.
=> Added Support for Mailing List "reply_preference" parameter

README.md
It's missing the `setApiKey` call and a hydrator that works with `Content-type: text/html` returned by postbin.
=> Provide a working debugging example in README

src/Api/Ip.php
`/v3/domains/{domain}/ips` is the correct endpoint per https://documentation.mailgun.com/en/latest/api-ips.html#ips
=> fix /v3/domains/{domain}/ips endpoint

src/Model/Message/ShowResponse.php
The response from the api is an array and not a string.
=> Bug fix with getContentIdMap return type

composer.json
It still uses the same API, just updated for PHP 7
=> Allow php-http/guzzle6-adapter ^2.0

.travis.yml, src/Mailgun/Api/Ip.php
The ips()->assign() method fails because the required parameter is misspelled. This appears to be in all releases, not just the 2.x branch.
=> Fix misspelled parameter

doc/index.md, src/Api/Domain.php, src/Api/HttpApi.php, src/Api/Ip.php, src/Api/MailingList/Member.php, src/Api/Message.php, src/Api/Suppression.php, src/Api/Tag.php, src/Api/Webhook.php, src/Mailgun.php, src/Model/Event/EventResponse.php, src/Model/MailingList/Member/IndexResponse.php, src/Model/MailingList/PagesResponse.php, tests/Api/TagTest.php, tests/Api/WebhookTest.php
Change webhook create() $url parameter from string to array to support
multiple URLs
Change webhook update() $url parameter from string to array yo support
multiple URLs
=> feat: add array support to webhook handling

src/Api/Stats.php, tests/Api/StatsTest.php
https://github.com/mailgun/mailgun-php/issues/628 method all() is not working and has no endpoint associated with it
```
[05-Oct-2020 16:50:34 UTC] PHP Fatal error:  Uncaught Mailgun\Exception\HttpClientException: The endpoint you have tried to access does not exist. Check if the domain matches the domain you have configure on Mailgun. in /var/www/mailgun-php/src/Exception/HttpClientException.php:78
Stack trace:
#0 /var/www/mailgun-php/src/Api/HttpApi.php(91): Mailgun\Exception\HttpClientException::notFound(Object(GuzzleHttp\Psr7\Response))
#1 /var/www/mailgun-php/src/Api/HttpApi.php(67): Mailgun\Api\HttpApi->handleErrors(Object(GuzzleHttp\Psr7\Response))
#2 /var/www/mailgun-php/src/Api/Stats.php(46): Mailgun\Api\HttpApi->hydrateResponse(Object(GuzzleHttp\Psr7\Response), …
```
=> removed unused method

src/Api/Ip.php, tests/Api/IpTest.php
This PR fixes a bug in assigning an IP to a domain.
Assigning an IP to a domain currently results in the following error:
```
[Mailgun\Exception\HttpClientException] The parameters passed to the API were invalid. Check your inputs!
either 'ip' or 'pool_id' parameter is required, but not both in /var/www/vendor/mailgun/mailgun-php/src/Mailgun/Exception/HttpClientException.php on line 72
Stack Trace:
#0 /var/www/vendor/mailgun/mailgun-php/src/Mailgun/Api/HttpApi.php(91): Mailgun\Exception\HttpClientException::badRequest(Object(GuzzleHttp\Psr7\Response))
#1 /var/www/vendor/mailgun/mailgun-php/src/Mailgun/Api/HttpApi.php(73): Mailgun\Api\HttpApi->handleErrors(Object(GuzzleHttp\Psr7\Response))
#2 /var/www/vendor/mailgun/mailgun-php/src/Mailgun/Api/Ip.php(96): …
```
=> Fix assigning Ip

src/Api/Domain.php, tests/Api/DomainTest.php
The Domains API allows assigning Ips upon creation.
https://documentation.mailgun.com/en/latest/api-domains.html#domains
This PR adds that ability to the PHP SDK.
=> Allow assigning a domain to a list of ips during creation

src/Api/Ip.php, src/Model/Ip/IndexResponse.php, tests/Api/Ip.php, tests/Model/Ip/IndexResponseTest.php
The GET /ips endpoint returns all IPs by default, shared ips if the dedicated parameter is false and dedicated ips only if the dedicated parameter is true. However, the SDK `Ip::index()` method always defaults to passing false, and has no ability to return all ips.
This PR fixes that so the default behavior for `Ip::index()` is to return all IPs (instead of shared IPs). This is more consistent with the API.
=> Change Ip::index() default to return all ips instead of shared ips

.github/workflows/php.yml, .gitignore, CHANGELOG.md, composer.json, tests/Api/StatsTest.php, tests/Api/TestCase.php, tests/HttpClient/RequestBuilderTest.php, tests/Message/BatchMessageTest.php, tests/Message/MessageBuilderTest.php
Closes #725
----
Before merging this new PR, we will wait for https://github.com/mailgun/mailgun-php/pull/726 to be merged so we can provide a new SDK version with the highly requested Email Validator feature.
This PR to enable PHP 8.0 support causes a BC Break so that it will be flagged as SDK 4.0.0
=> PHP 8.x support

src/Model/Stats/TotalResponseItem.php, tests/Api/StatsTest.php
Currently the TotalResponseItem class does not parse opened, clicked, unsubscribed, and stored events.
This PR solves that.
It also adds tests for the new events, and adds testing of totals in the response
=> Add additional events to TotalResponseItem

src/Api/HttpApi.php, src/Api/Pagination.php, src/Hydrator/ArrayHydrator.php, src/Hydrator/Hydrator.php, src/Hydrator/ModelHydrator.php, src/Hydrator/NoopHydrator.php
This is just a simple little PR that addresses the following message you get when you run PHPStan's static analysis on the project:
```
------ ------------------------------------------------------------------------------------------------------ 
Line   Hydrator/ModelHydrator.php                                                                            
------ ------------------------------------------------------------------------------------------------------ 
45     Parameter #1 $callback of function call_user_func expects callable(): mixed, non-empty-string given.  
------ ------------------------------------------------------------------------------------------------------
```
The fix just changes the `callable` to use the array syntax for static methods seen in the [official PHP …
=> Fix PHPStan error reported for ModelHydrator::hydrate (and tighten $class param type for all hydrator classes)

composer.json, tests/Api/DomainTest.php, tests/Api/EmailValidationTest.php, tests/Api/EmailValidationV4Test.php, tests/Api/EventTest.php, tests/Api/Ip.php, tests/Api/MailingList/MemberTest.php, tests/Api/MailingListTest.php, tests/Api/MessageTest.php, tests/Api/RouteTest.php, tests/Api/StatsTest.php, tests/Api/TagTest.php, tests/Api/TestCase.php, tests/Exception/HttpClientExceptionTest.php
The `php-http/guzzle7-adapter` is not needed anymore. We can use guzzle or symfony's http client instead. 
Disclaimer: I maintain all three packages.
=> Update dev dependencies

src/Message/BatchMessage.php, src/Message/MessageBuilder.php, src/Message/README.md
Add function to set the template and only throw the error message when text, html and template variables are missing.
Also mention "setTextBody", "setHtmlBody" and the new "setTemplate" in the readme.
Before this, you had to use "setMessage" function to set all the variables including from, to, template, text/html etc if you wanted to use templates.
=> Add template support when using BatchMessage

README.md
Laravel comes with Mailgun support
=> chore: added Laravel Mailgun driver info into readme

.gitignore, CHANGELOG.md, phpunit.xml.dist, phpunit.xml.dist.bak, src/Message/BatchMessage.php, src/Model/Ip/IndexResponse.php, tests/Message/BatchMessageTest.php
- BatchMessage generates "invalid" JSON for recipients with an empty set of recipient-variables
- Use null coalescing operator in IndexResponse.php
=> Fixed issues

src/Model/Suppression/Bounce/Bounce.php, src/Model/Suppression/Complaint/Complaint.php, src/Model/Suppression/Unsubscribe/Unsubscribe.php, src/Model/Suppression/Whitelist/DeleteResponse.php, src/Model/Suppression/Whitelist/Whitelist.php, tests/Model/Suppression/Whitelists/ShowResponseTest.php
Attempt to fix issue #878 and added simple test for validation.
Particularly, for `final class DeleteResponse` , replaced 'new static()' with the more appropriate 'new self()', since it's a final class.
=> Bugfix: TypeError caused by improper use of `new self()` instead of `new static()` in base class method (#878)

README.md
According to the source, Mailgun uses `Discovery\Psr17FactoryDiscovery` and `Psr18ClientDiscovery`; thus, docs should like to factory and not message implementations.
Edit: just noticed that the mysterious package forced in my dependencies is indeed a provider of `psr/http-factory-implementation`, so it looks like my guesses for this commit seem correct :joy:
Related to #889.
=> Fix README with the correct list of PSR-17 packages

doc/index.md, src/Api/Domain.php, src/Api/HttpClient.php, src/Api/Route.php, src/Api/Suppression.php, src/Api/Suppression/Bounce.php, src/Api/Suppression/Complaint.php, src/Api/Suppression/Unsubscribe.php
I found that URLs with out `/en/latest` are resulting in 404 errors:
- https://documentation.mailgun.com/api_reference.html
- https://documentation.mailgun.com/api-domains.html
- https://documentation.mailgun.com/api-routes.html
- https://documentation.mailgun.com/api-suppressions.html
Just adding this missing `/en/latest` fixes them.
I also fixed the https://documentation.mailgun.com/user_manual.html#um-spam-filter although that link seems to be incorrectly placed there, I'm not really sure, you'll guys have to take a look at that one.
=> fix documentation URLs

src/Api/Domain.php, src/Api/DomainV4.php, src/Api/MailingList/Member.php, src/Api/Route.php, src/Api/Suppression/Complaint.php, src/Api/Suppression/Unsubscribe.php, src/Mailgun.php, src/Message/Exceptions/MissingRequiredParameter.php, src/Message/MessageBuilder.php
Fixed deprecations notices in PHP 8.4 like `Implicitly marking parameter ... as nullable is deprecated, the explicit nullable type must be used instead`
=> Fixed PHP 8.4 deprecations

src/Api/DomainV4.php, src/Model/Domain/UseAutomaticSenderSecurity.php
=> Add useAutomaticSenderSecurity support in DomainV4
