- README.md
We should be proud that we have a community that build stuff for us and help developers to integrate `mailgun-php` into a framework.
> Added links to packages that integrate mailgun-php to frameworks

- composer.json
- src/Mailgun/Connection/RestClient.php
> Bumped to guzzlehttp/guzzle:~6.0

- README.md
The correct value is a boolean
> Change string "false" to boolean false in README

- src/Mailgun/Connection/Exceptions/GenericHTTPError.php
- src/Mailgun/Connection/Exceptions/InvalidCredentials.php
- src/Mailgun/Connection/Exceptions/MissingEndpoint.php
- src/Mailgun/Connection/Exceptions/MissingRequiredParameters.php
- src/Mailgun/Connection/Exceptions/NoDomainsConfigured.php
- src/Mailgun/Connection/RestClient.php
- src/Mailgun/Constants/Api.php
- src/Mailgun/Constants/ExceptionMessages.php
- src/Mailgun/Lists/OptInHandler.php
- src/Mailgun/Mailgun.php
- src/Mailgun/Messages/BatchMessage.php
- src/Mailgun/Messages/Exceptions/InvalidParameter.php
- src/Mailgun/Messages/Exceptions/InvalidParameterType.php
- src/Mailgun/Messages/Exceptions/MissingRequiredMIMEParameters.php
- src/Mailgun/Messages/Exceptions/TooManyParameters.php
- src/Mailgun/Messages/MessageBuilder.php
- tests/Bootstrap.php
- tests/Mailgun/Tests/Lists/OptInHandlerTest.php
- tests/Mailgun/Tests/MailgunTest.php
- tests/Mailgun/Tests/Messages/BatchMessageTest.php
- tests/Mailgun/Tests/Messages/MessageBuilderTest.php
- tests/Mailgun/Tests/Messages/StandardMessageTest.php
- tests/Mailgun/Tests/Mock/Connection/TestBroker.php
- tests/Mailgun/Tests/Mock/Mailgun.php
This PR is applying most common PSR Standards via these 3 tools:
- [StyleCI](https://styleci.io)
- [PHP CS Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer)
- [PHP Code Sniffer](https://github.com/squizlabs/PHP_CodeSniffer)
This PR is replacing the old PR I added some time ago (https://github.com/mailgun/mailgun-php/pull/106) now closed, and I got a new request to add this PR again, but fixing the updated code.
| Q             | A      |
|---------------|--------|
| Branch        | v2.1.2 |
| Bug fix?      | No     |
| New feature?  | No     |
| BC breaks?    | No     |
| Deprecations? | No     |
| Tests pass?   | Yes    |
| Fixed tickets |        |
| License       |        |
| Doc PR        |        |
> Apply PSR Standards

- README.md
| Q             | A      |
|---------------|--------|
| Branch        | v2.1.2 |
| Bug fix?      | No     |
| New feature?  | No     |
| BC breaks?    | No     |
| Deprecations? | No     |
| Tests pass?   | Yes    |
| Fixed tickets | https://github.com/mailgun/mailgun-php/issues/136    |
| License       |        |
| Doc PR        |        |
Remove `Library Download` link as suggested by @Nyholm on Issue #136
> Remove `Library Download` link/paragraph

- README.md
Updated headings and made it more clear what to do to install the library.
> Updated installation docs

- src/Mailgun/Messages/MessageBuilder.php
I just rewrote the function. I did not change any behavior.
> Reduce code complexity on addInlineImage

- src/Mailgun/Connection/RestClient.php
- tests/Functional/InlineFileTest.php
- tests/Functional/NoSamePostNameTest.php
> Make sure we use proper POST data arrays

- src/Mailgun/Messages/README.md
> Updated signature for addAttachment

- .editorconfig
- .gitattributes
- .php_cs
- .scrutinizer.yml
- .styleci.yml
- src/Mailgun/Connection/RestClient.php
- src/Mailgun/Mailgun.php
- src/Mailgun/Messages/MessageBuilder.php
- tests/Functional/FileFromMemoryTest.php
- tests/Functional/SendMessageTest.php
- tests/MailgunTest.php
- tests/Messages/BatchMessageTest.php
- tests/Messages/ComplexMessageTest.php
- tests/Messages/MessageBuilderTest.php
- tests/Messages/StandardMessageTest.php
This will have some settings for style ci, scrutinizer and editors.
> Added meta files

- .travis.yml
- composer.json
- phpunit.xml.dist
Simplify the travis config and make sure you can run all relevant tests by `composer test`
> SImplefied travis config and added composer scripts

- src/Mailgun/Mailgun.php
- src/Mailgun/Serializer/ModelSerializer.php
> Rename ObjectSerializer to ModelSerializer

- src/Mailgun/Api/Domain.php
- src/Mailgun/Api/HttpApi.php
- src/Mailgun/Api/Stats.php
> Rename AbstractApi to HttpApi

- src/Mailgun/Api/Domain.php
- src/Mailgun/Api/HttpApi.php
- src/Mailgun/Mailgun.php
- src/Mailgun/RequestBuilder.php
- tests/Api/TestCase.php
- tests/RequestBuilderTest.php
We inject every dependency (eg RequestFactory and MultipartStreamBuilder) and we do not have to use postMultipart.
This will fix #205
> Introduce a request builder.

- src/Mailgun/Mailgun.php
> Rename functions to reflect the API

- src/Mailgun/Api/Domain.php
- tests/Integration/DomainApiTest.php
> Fixed integration tests

- .gitignore
.DS_STORE
.idea 
etc should be in the global gitignore. 
smoketest.php and other test files should go in test/.
> Clean up gitignore.

- composer.json
- phpunit.xml.dist
> Disable integration tests until they are improved

- README.md
Explain how you get domain objects, arrays or PSR7 responses
> Updated response section

- src/Mailgun/Api/Webhook.php
- src/Mailgun/Resource/Api/Webhook/BaseResponse.php
- src/Mailgun/Resource/Api/Webhook/CreateResponse.php
- src/Mailgun/Resource/Api/Webhook/DeleteResponse.php
- src/Mailgun/Resource/Api/Webhook/IndexResponse.php
- src/Mailgun/Resource/Api/Webhook/ShowResponse.php
- src/Mailgun/Resource/Api/Webhook/UpdateResponse.php
> Added Webhook API

- src/Mailgun/Api/HttpApi.php
- src/Mailgun/Connection/RestClient.php
- src/Mailgun/Messages/BatchMessage.php
- src/Mailgun/Messages/MessageBuilder.php
- src/Mailgun/Resource/Api/Domain/CreateResponse.php
- src/Mailgun/Resource/Api/Domain/Domain.php
- src/Mailgun/Resource/Api/Message/ShowResponse.php
- src/Mailgun/Resource/Api/Stats/AllResponseItem.php
A set of minor updates reported by Scrutinizer CI.
> Minor amends reported by Scrutinizer CI

- .scrutinizer.yml
> Increase timeout for code coverage

- src/Mailgun/Connection/RestClient.php
- src/Mailgun/RequestBuilder.php
This will support bounderies with non whitespace
> Add quotes around the boundary.

- README.md
> Removed framework version number

- src/Mailgun/Messages/MessageBuilder.php
- tests/Messages/MessageBuilderTest.php
> Fix setting Reply-To multiple times

- src/Mailgun/Mailgun.php
- tests/Functional/FileFromMemoryTest.php
- tests/Functional/InlineFileTest.php
- tests/Functional/MockedMailgun.php
- tests/Functional/NoSamePostNameTest.php
- tests/Functional/SendMessageTest.php
It make it easier to create an instance of the API
> Added factory methods

- tests/Api/RoutesTest.php
> Added test for Route::Create

- src/Mailgun/Api/Domain.php
- src/Mailgun/Api/Event.php
- src/Mailgun/Api/HttpApi.php
- src/Mailgun/Api/Message.php
- src/Mailgun/Api/Pagination.php
- src/Mailgun/Api/Routes.php
- src/Mailgun/Api/Stats.php
- src/Mailgun/Api/Suppression/Bounce.php
- src/Mailgun/Api/Suppression/Complaint.php
- src/Mailgun/Api/Suppression/Unsubscribe.php
- src/Mailgun/Api/Tag.php
- src/Mailgun/Api/Webhook.php
- src/Mailgun/Exception/DeserializeException.php
- src/Mailgun/Exception/HttpClientException.php
- src/Mailgun/Exception/HttpServerException.php
- src/Mailgun/Exception/InvalidArgumentException.php
- src/Mailgun/Exception/UnknownErrorException.php
- src/Mailgun/Hydrator/ArrayHydrator.php
- src/Mailgun/Hydrator/Hydrator.php
- src/Mailgun/Hydrator/ModelHydrator.php
- src/Mailgun/Hydrator/NoopHydrator.php
- tests/Api/TestCase.php
I renamed in "HydrateResponse" and I moved out the error checking to a separate function.
> Improving safe hydrate

- src/Mailgun/HttpClient/Plugin/History.php
- src/Mailgun/HttpClientConfigurator.php
- src/Mailgun/Mailgun.php
This will fix #267 
FYI @pbowyer
> Make sure we can get the last response from the API again.

- src/Mailgun/Messages/MessageBuilder.php
- tests/Functional/MessageBuilderHeaderTest.php
- tests/Messages/MessageBuilderTest.php
Fix for issue https://github.com/mailgun/mailgun-php/issues/254
> Bug fix - Allow adding custom headers with non-array value

- src/Mailgun/Api/Route.php
- src/Mailgun/Mailgun.php
- src/Mailgun/Model/Route/Action.php
- src/Mailgun/Model/Route/Response/CreateResponse.php
- src/Mailgun/Model/Route/Response/DeleteResponse.php
- src/Mailgun/Model/Route/Response/IndexResponse.php
- src/Mailgun/Model/Route/Response/ShowResponse.php
- src/Mailgun/Model/Route/Response/UpdateResponse.php
- src/Mailgun/Model/Route/Route.php
- tests/Api/RouteTest.php
Class names should be in singlular
> Renamed Routes to Route

- src/Mailgun/Api/HttpApi.php
Build a query encoded request strings and set proper headers.
This will fix issue #281
> Do not use json request body

- src/Mailgun/Model/Message/ShowResponse.php
> Adding attachments and content id map

- src/Mailgun/Exception/HttpClientException.php
> Make error responses accessable

- README.md
- src/Mailgun/Mailgun.php
Make sure we use factories
TODO
> Fix new constructor

- src/Mailgun/Api/Event.php
> Removed old pagination methods

- src/Mailgun/Api/Suppression/Complaint.php
> Updated function parameters

- src/Mailgun/Api/Webhook.php
- src/Mailgun/HttpClientConfigurator.php
- src/Mailgun/Mailgun.php
This will fix #321 
I just moved the function to the Webhook API
> Implemented a way to verify webhook signature

- .travis.yml
This PR will also remove the "IS_PR"-check
> Always run "composer test-all"

- README.md
- doc/attachments.md
- doc/index.md
- doc/pagination.md
> Added documentation for the API classes

- doc/index.md
- src/Mailgun/Api/Message.php
- tests/Api/MessageTest.php
- tests/MailgunTest.php
Make sure we support Mime. This is not a BC.. I'll explain in the comments.
> Support mime messages

- src/Mailgun/RequestBuilder.php
> Make sure to reset the multipartStreamBuilder

- composer.json
There were no changes from 0.2.0 to 1.0.0
> Use stable version of multipart stream builder

- src/Mailgun/Model/Domain/DnsRecord.php
> Add cached property for DNS record

- doc/index.md
- src/Mailgun/Api/Domain.php
- src/Mailgun/Model/Domain/VerifyResponse.php
- tests/Integration/DomainApiTest.php
> Add domain verification

- src/Mailgun/Model/Webhook/IndexResponse.php
response contains data inside of 'webhooks' array
> fix to index webhooks method

- README.md
- src/Mailgun/Constants/ExceptionMessages.php
- src/Mailgun/Exception/HttpClientException.php
Attempt to solve the confusion about the Exception mentioned in https://github.com/mailgun/mailgun-php/issues/178.
> Updated EXCEPTION_MISSING_ENDPOINT and README accordingly

- doc/pagination.md
> Fix small typo in docs

- doc/index.md
> Fix typo in complaints method

- src/Mailgun/Api/Message.php
> fixed typo

- CHANGELOG.md
> Prepare for 2.4

- src/Mailgun/Model/Suppression/Unsubscribe/IndexResponse.php
This should cover point 3 of issue #390
> Implement getTotalCount and add doc descriptions

- src/Mailgun/Connection/Exceptions/GenericHTTPError.php
- src/Mailgun/Constants/Api.php
- src/Mailgun/Constants/ExceptionMessages.php
- src/Mailgun/Model/Suppression/Unsubscribe/Unsubscribe.php
- tests/Lists/OptInHandlerTest.php
- tests/Messages/BatchMessageTest.php
- tests/Messages/ComplexMessageTest.php
- tests/Messages/StandardMessageTest.php
- tests/Mock/Mailgun.php
- tests/Model/Suppression/Unsubscribe/UnsubscribeTest.php
Hi,
Actually tags from v3 are not fulfilled.
This PR fixes the issue without introducing BC.
> feat(unsubscribe): Handle tags in Unsubscribe v3 api.

- composer.json
- src/Mailgun/Api/Message.php
- src/Mailgun/Mailgun.php
- src/Mailgun/Message/BatchMessage.php
- src/Mailgun/Message/Exceptions/LimitExceeded.php
- src/Mailgun/Message/Exceptions/MissingRequiredParameter.php
- src/Mailgun/Message/Exceptions/RuntimeException.php
- src/Mailgun/Message/Exceptions/TooManyRecipients.php
- src/Mailgun/Message/MessageBuilder.php
- src/Mailgun/Message/README.md
- src/Mailgun/Messages/BatchMessage.php
- src/Mailgun/Messages/MessageBuilder.php
- tests/Message/BatchMessageTest.php
- tests/Message/MessageBuilderTest.php
- tests/Messages/ComplexMessageTest.php
Lots of cleanup of the old code.
> Ported MessageBuilder and BatchMessage

- src/Mailgun/Api/Suppression/Complaint.php
- tests/Api/DomainTest.php
- tests/Api/EventTest.php
- tests/Api/MessageTest.php
- tests/Api/RouteTest.php
- tests/Api/Suppression/BounceTest.php
- tests/Api/Suppression/ComplaintTest.php
- tests/Api/Suppression/UnsubscribeTest.php
- tests/Api/SuppressionTest.php
- tests/Api/TestCase.php
- tests/Api/WebhookTest.php
Sorry for another massive PR. 
This just adds tests to our API endpoints. It also adds some features to the `Api\TestCase` that makes it easier to write tests.
> Add more tests for our APIs

- src/Mailgun/Mailgun.php
This will make it easier to choose the new EU region. 
This is related to #471
> Add endpoint to the create function

- src/Mailgun/Model/Domain/UpdateConnectionResponse.php
- tests/Model/BaseModelTest.php
- tests/Model/Domain/ConnectionResponseTest.php
- tests/Model/Domain/CreateCredentialResponseTest.php
- tests/Model/Domain/CreateResponseTest.php
- tests/Model/Domain/CredentialResponseItemTest.php
- tests/Model/Domain/CredentialResponseTest.php
- tests/Model/Domain/DeleteCredentialResponseTest.php
- tests/Model/Domain/DeleteResponseTest.php
- tests/Model/Domain/DnsRecordTest.php
- tests/Model/Domain/DomainTest.php
- tests/Model/Domain/IndexResponseTest.php
- tests/Model/Domain/ShowResponseTest.php
- tests/Model/Domain/UpdateConnectionResponseTest.php
- tests/Model/Domain/UpdateCredentialResponseTest.php
- tests/Model/Domain/VerifyResponseTest.php
- tests/Model/Suppression/Unsubscribe/UnsubscribeTest.php
Starting to add tests for our models. 
The JSON is copied from mailgun documentation
> Added tests for our models

- src/Mailgun/Api/Attachment.php
- src/Mailgun/Mailgun.php
- src/Mailgun/Model/Attachment/Attachment.php
- tests/Api/AttachmentTest.php
- tests/Api/TagTest.php
- tests/Model/BaseModelTest.php
- tests/Model/Domain/ConnectionResponseTest.php
- tests/Model/Domain/CreateCredentialResponseTest.php
- tests/Model/Domain/CreateResponseTest.php
- tests/Model/Domain/CredentialResponseItemTest.php
- tests/Model/Domain/CredentialResponseTest.php
- tests/Model/Domain/DeleteCredentialResponseTest.php
- tests/Model/Domain/DeleteResponseTest.php
- tests/Model/Domain/DnsRecordTest.php
- tests/Model/Domain/DomainTest.php
- tests/Model/Domain/IndexResponseTest.php
- tests/Model/Domain/ShowResponseTest.php
- tests/Model/Domain/UpdateConnectionResponseTest.php
- tests/Model/Domain/UpdateCredentialResponseTest.php
- tests/Model/Domain/VerifyResponseTest.php
Related to #398 
I do not want to create a generic "get" function. That is why I added some regex. However, im not sure the regex is okey. This needs some testing.
> Added a way to get attachments

- src/Mailgun/Message/MessageBuilder.php
This way, it's the same as `addToRecipient` and `addCcRecipient`
> MessageBuilder > addBccRecipient > Make $variables optional

- CHANGELOG.md
- composer.json
> Added support for HTTPlug 2.0

- src/Mailgun/Model/Stats/TotalResponseItem.php
- tests/Model/Stats/TotalResponseTest.php
> Added "complaints" to TotalResponse

- src/Mailgun/Api/Ip.php
- src/Mailgun/Model/Ip/IndexResponse.php
- src/Mailgun/Model/Ip/ShowResponse.php
- src/Mailgun/Model/Ip/UpdateResponse.php
- tests/Model/Ip/IndexResponseTest.php
- tests/Model/Ip/ShowResponseTest.php
- tests/Model/Ip/UpdateResponseTest.php
> Added IP API class, models and test

- CHANGELOG.md
Waiting for the Mailing Lists PR before to merge and release
> Prepare for 2.8.0

- composer.json
> Remove php-http/message

- src/Message/MessageBuilder.php
BC Breaks - to be merged to 3.0
> MessageBuilder setters entirely fluent

- src/Mailgun/Mailgun.php
Note that this PR is to the 2.x branch.
> Added Mailgun::ips()

- .php_cs
- src/Api/Domain.php
- src/Api/MailingList/Member.php
- src/Message/BatchMessage.php
- src/Message/MessageBuilder.php
- src/Model/Domain/DnsRecord.php
- tests/Api/TestCase.php
- tests/Model/Domain/UpdateConnectionResponseTest.php
- tests/Model/Domain/VerifyResponseTest.php
> Added proper PHP CS fixer rules

- README.md
We don’t really need this badge.
> Removed some badges

- src/Api/Tag.php
- src/Model/Tag/CountryResponse.php
- src/Model/Tag/DeviceResponse.php
- src/Model/Tag/ProviderResponse.php
- tests/Model/Tag/CountryResponseTest.php
- tests/Model/Tag/DeviceResponseTest.php
- tests/Model/Tag/ProviderResponseTest.php
> Adding tag aggregates

- CHANGELOG.md
There is still a long way to go. But I just wanted to start on a change log .
> Added changelog for 3.0.0

- src/Model/ApiResponse.php
- src/Model/Attachment/Attachment.php
- src/Model/Domain/AbstractDomainResponse.php
- src/Model/Domain/ConnectionResponse.php
- src/Model/Domain/CreateCredentialResponse.php
- src/Model/Domain/CredentialResponse.php
- src/Model/Domain/CredentialResponseItem.php
- src/Model/Domain/DeleteCredentialResponse.php
- src/Model/Domain/DeleteResponse.php
- src/Model/Domain/DnsRecord.php
- src/Model/Domain/Domain.php
- src/Model/Domain/IndexResponse.php
- src/Model/Domain/ShowResponse.php
- src/Model/Domain/UpdateConnectionResponse.php
- src/Model/Domain/UpdateCredentialResponse.php
It feels good to remove code. But this process is slow..
I've done Attachments and Domain. Will continue with other models in a separate PR. 
This is part of #532
> Updating models to PHP 7 for Domain and Attachments

- .travis.yml
- src/Api/MailingList/Member.php
- src/Model/Event/Event.php
- src/Model/Event/EventResponse.php
- src/Model/Ip/IndexResponse.php
- src/Model/Ip/ShowResponse.php
- src/Model/Ip/UpdateResponse.php
Two more namespaces updated to PHP 7 code.
> Fixed PHP7 on Event model and Ip model

- .travis.yml
- phpstan.neon
- src/Model/MailingList/CreateResponse.php
- src/Model/MailingList/DeleteResponse.php
- src/Model/MailingList/MailingList.php
- src/Model/MailingList/Member/CreateResponse.php
- src/Model/MailingList/Member/DeleteResponse.php
- src/Model/MailingList/Member/IndexResponse.php
- src/Model/MailingList/Member/Member.php
- src/Model/MailingList/Member/ShowResponse.php
- src/Model/MailingList/Member/UpdateResponse.php
- src/Model/MailingList/PagesResponse.php
- src/Model/MailingList/ShowResponse.php
- src/Model/MailingList/UpdateResponse.php
- src/Model/Message/SendResponse.php
- src/Model/Message/ShowResponse.php
- src/Model/Route/Action.php
- src/Model/Route/CreateResponse.php
- src/Model/Route/DeleteResponse.php
- src/Model/Route/IndexResponse.php
- src/Model/Route/Route.php
- src/Model/Route/ShowResponse.php
- src/Model/Route/UpdateResponse.php
- tests/Message/BatchMessageTest.php
> Moved MailingList, Message and Route to PHP7 code

- src/Model/Suppression/Bounce/Bounce.php
- src/Model/Suppression/Bounce/IndexResponse.php
- src/Model/Suppression/Complaint/Complaint.php
- src/Model/Suppression/Complaint/IndexResponse.php
- src/Model/Suppression/Unsubscribe/IndexResponse.php
- src/Model/Suppression/Unsubscribe/Unsubscribe.php
- src/Model/Tag/IndexResponse.php
- src/Model/Tag/UpdateResponse.php
> Minor cleanup and cs

- src/Mailgun.php
Reverts mailgun/mailgun-php#552
> Revert "Missing method for the MailingList API endpoints?"

- README.md
This should fix https://github.com/mailgun/mailgun-php/issues/556
> Include API endpoint in README

- README.md
Add link for Drupal in README.md
> mailgun | Drupal

- src/HttpClient/HttpClientConfigurator.php
- src/Model/Webhook/ShowResponse.php
- src/Model/Webhook/UpdateResponse.php
> Use PSR-17 and mark classes as final

- src/Api/Domain.php
- src/Api/Event.php
- src/Api/Ip.php
- src/Api/MailingList.php
- src/Api/MailingList/Member.php
- src/Api/Message.php
- src/Api/Route.php
- src/Api/Stats.php
- src/Api/Tag.php
- src/Api/Webhook.php
> Make sure the doc block link is updated

- doc/index.md
Updated doc for sending a mime message based on new Swiftmailer version and lib parameters.
> Update mime message docs

- src/Api/MailingList/Member.php
- src/Api/Route.php
- src/HttpClient/RequestBuilder.php
- src/Mailgun.php
- tests/Api/MailingList/MemberTest.php
- tests/Api/RouteTest.php
These are just minors. 
Will fix #581, fix #582, fix #584
> Fixed a few PRs and some cleanup

- src/Mailgun.php
I've added the missing `mailingList` method 😄 
Also, I sorted all api methods by name - hope it's ok.
> Fixed missing mailinglist

- .gitignore
- src/Api/HttpApi.php
- src/Exception/HttpClientException.php
- tests/Exception/HttpClientExceptionTest.php
I want to consider forbidden response ( etc. Account disable) instead of UnknownException, So this is a way to get it.
> Add Forbidden response

- README.md
Link https://packagist.org/providers/php-http/client-implementation
> Link Packagist's PSR7 Implementations and Clients

- src/Api/Suppression/Unsubscribe.php
- tests/Api/Suppression/UnsubscribeTest.php
ref https://documentation.mailgun.com/en/latest/api-suppressions.html#delete-a-single-unsubscribe
> Add unsubscribe delete API with parameter

- .php_cs
- src/Api/Domain.php
- src/Api/HttpApi.php
- src/Api/Ip.php
- src/Api/MailingList/Member.php
- src/Api/Message.php
- src/Api/Suppression.php
- src/Api/Tag.php
- src/Api/Webhook.php
- src/Mailgun.php
- src/Model/Domain/AbstractDomainResponse.php
- src/Model/Event/EventResponse.php
- src/Model/MailingList/Member/IndexResponse.php
- src/Model/MailingList/PagesResponse.php
- src/Model/Suppression/BaseResponse.php
- src/Model/Webhook/BaseResponse.php
- tests/Api/TagTest.php
- tests/Api/WebhookTest.php
Fix phpstan and php-cs-fixer errors
> build: fix style and phpstan

- README.md
https://github.com/Bogardo/Mailgun is archived
> remove deprecated pacakge from suggestions

- src/Model/Event/Event.php
- tests/Model/Event/EventResponseTest.php
https://github.com/mailgun/mailgun-php/issues/677
Support **log-level** property for the Event model
> added unmapped proeprty logLevel to Event model

- src/Api/Domain.php
- src/Model/Domain/ClickTracking.php
- src/Model/Domain/OpenTracking.php
- src/Model/Domain/TrackingResponse.php
- src/Model/Domain/UnsubscribeTracking.php
- src/Model/Domain/UpdateClickTrackingResponse.php
- src/Model/Domain/UpdateOpenTrackingResponse.php
- src/Model/Domain/UpdateUnsubscribeTrackingResponse.php
- tests/Api/DomainTest.php
- tests/Model/Domain/ClickTrackingTest.php
- tests/Model/Domain/OpenTrackingTest.php
- tests/Model/Domain/TrackingResponseTest.php
- tests/Model/Domain/UnsubscribeTrackingTest.php
- tests/Model/Domain/UpdateClickTrackingResponseTest.php
- tests/Model/Domain/UpdateOpenTrackingResponseTest.php
- tests/Model/Domain/UpdateUnsubscribeTrackingResponseTest.php
> Domain tracking

- src/Api/MailingList.php
- src/Model/MailingList/ValidateResponse.php
- src/Model/MailingList/ValidationCancelResponse.php
- src/Model/MailingList/ValidationStatusDownloadUrl.php
- src/Model/MailingList/ValidationStatusResponse.php
- src/Model/MailingList/ValidationStatusSummary.php
- src/Model/MailingList/ValidationStatusSummaryResult.php
- src/Model/MailingList/ValidationStatusSummaryRisk.php
- tests/Api/MailingListTest.php
- tests/Model/MailingList/ValidateResponseTest.php
- tests/Model/MailingList/ValidationCancelResponseTest.php
- tests/Model/MailingList/ValidationStatusDownloadUrlTest.php
- tests/Model/MailingList/ValidationStatusResponseTest.php
- tests/Model/MailingList/ValidationStatusSummaryResultTest.php
- tests/Model/MailingList/ValidationStatusSummaryRiskTest.php
- tests/Model/MailingList/ValidationStatusSummaryTest.php
https://github.com/mailgun/mailgun-php/issues/633
https://documentation.mailgun.com/en/latest/api-mailinglists.html#examples
> Mailing List Validation

- src/Api/HttpApi.php
- src/Api/Suppression.php
- src/Api/Suppression/Whitelist.php
- src/Model/Suppression/Whitelist/CreateResponse.php
- src/Model/Suppression/Whitelist/DeleteAllResponse.php
- src/Model/Suppression/Whitelist/DeleteResponse.php
- src/Model/Suppression/Whitelist/ImportResponse.php
- src/Model/Suppression/Whitelist/IndexResponse.php
- src/Model/Suppression/Whitelist/ShowResponse.php
- src/Model/Suppression/Whitelist/Whitelist.php
- tests/Api/Suppression/WhitelistTest.php
- tests/Api/SuppressionTest.php
- tests/Model/Suppression/Whitelists/CreateResponseTest.php
- tests/Model/Suppression/Whitelists/DeleteAllResponseTest.php
- tests/Model/Suppression/Whitelists/DeleteResponseTest.php
- tests/Model/Suppression/Whitelists/ImportResponseTest.php
- tests/Model/Suppression/Whitelists/IndexResponseTest.php
- tests/Model/Suppression/Whitelists/ShowResponseTest.php
- tests/Model/Suppression/Whitelists/WhitelistTest.php
> Suppression Whitelists

- src/Api/Tag.php
- src/Model/Tag/IndexResponse.php
- tests/Api/TagTest.php
- tests/Model/Tag/IndexResponseTest.php
https://github.com/mailgun/mailgun-php/issues/700
> added pagination to tags

- CHANGELOG.md
@DavidGarciaCat  feel free to merge and release this if you think it is valid.
> Prepare for 3.3.0

- src/Api/HttpApi.php
- tests/Api/EmailValidationV4Test.php
https://github.com/mailgun/mailgun-php/issues/737
> fix double urlencoding

- src/Api/HttpApi.php
- src/Exception/HttpClientException.php
- tests/Exception/HttpClientExceptionTest.php
Due to the doc - https://documentation.mailgun.com/en/latest/api-intro.html#status-codes
> Support for HTTP 429 Too Many Requests code

- .github/workflows/static.yml
- psalm.baseline.xml
This is just a small refresh to the analyzers. 
With this change, psalm, phpstan and php-cs-fixer will make Github PR comments.
> Update static analyzers

- README.md
Buzz is a great client, but I rather recommend using Symfony. 
One can argue that we should recommend Guzzle instead but Symfony is way more well maintained. 
Disclaimer: I am part of the team maintaining Symfony, the team for Guzzle and Im also maintaining Buzz.
> Update links and remove Buzz example

- tests/Api/MailboxesTest.php
This will fix the CI after merging #781
> Fixed broken CI

- composer.json
- src/Message/README.md
Fixed typos in the Batch Message example. Added dependency requirement in the Message Builder example. Reorganized the Message Builder example for uniformity.
> Update Message Builder Documentation

- .github/workflows/static.yml
- .gitignore
- .php-cs-fixer.php
- src/HttpClient/RequestBuilder.php
- src/Message/MessageBuilder.php
- src/Model/EmailValidationV4/Job.php
- src/Model/EmailValidationV4/Preview.php
- tests/Api/DomainTest.php
- tests/Api/EventTest.php
- tests/HttpClient/RequestBuilderTest.php
- tests/Message/MessageBuilderTest.php
Signed-off-by: Alexander Mykhailenko <mihaskep@gmail.com>
> Prevent Uncaught InvalidArgumentException

- src/Api/Domain.php
- src/Model/Domain/WebPrefixResponse.php
- tests/Api/DomainTest.php
- tests/Model/Domain/WebPrefixResponseTest.php
Add support for updating domain CNAME used for tracking opens and clicks.
> Support updating CNAME used for tracking opens and clicks
